export const refs = {
  body: document.querySelector('body'),
  firstVisit: document.querySelector('.container'),
  header: document.querySelector('.header'),
  form: document.querySelector('.inputs'),
  mainPart: document.querySelector('.main-part'),
  cardContainer: document.querySelector('.card-container'),
  closeModalBtn: document.querySelector('[data-modal-close]'),
  modal: document.querySelector('[data-modal]'),
  footer: document.querySelector('.footer'),
  headerSection: document.querySelector('.header'),
  modalContentContainer: document.querySelector('.modal-data-container'),
  paginationList: document.querySelector('.pagination-list'),
  backdrop: document.querySelector('.backdrop'),
};
